### ISSUE TITLE
Unprocessed SCSS is getting into CSS

### ISSUE THREAD

**Issue by waldoj** [flexion/hud-disaster-data#97]
[`app.css` has some unprocessed SCSS included in it](https://github.com/flexion/hud-disaster-data/blob/master/app/public/assets/css/app.css#L659). Every `h` tag is sized with `rem(nnpx)`, e.g.:
```css
h1 {
  font-size: rem(40px);
  font-weight: 700; }

h2 {
  font-size: rem(30px);
  font-weight: 700; }
```
While this is valid SCSS, it isn't valid CSS. I'm not sure what browsers are making of this, but it's got to confuse the heck out of their CSS renderer.

FWIW, it looks like something is going wrong in processing [these SCSS variables](https://github.com/flexion/hud-disaster-data/blob/master/app/public/assets/_scss/00-presets/_vars.scss#L76).
